name: ClanPlugin
version: '${version}'
main: de.peaqe.clanplugin.ClanPlugin
api-version: '1.20'

depend:
  - Vault

softdepend:
  - PlaceholderAPI

commands:
  clan:
    aliases:
      - guild
      - g
  clanchat:
    aliases:
      - guildchat
      - gc
