name: latetime-clan
version: '${version}'
main: de.peaqe.latetimeclan.LateTimeClan
api-version: '1.20'

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  clan:
    aliases:
      - guild
      - g
  clanchat:
    aliases:
      - guildchat
      - gc
